window.PROJECTS_DATA=[
{id:'ai-butler',highlight:'AI conversation flow, UI design system refresh, and motion for small-screen devices',coverNatural:true,projectType:'Hardware–Software Integration · Interaction Design',timeline:'2023 – Now',platform:'Android App',timelineFirst:true,coverHeadline:'From a single sensory experience to a scalable system.',labels:['Hardware–Software Integration','Interaction Design'],tag:'Smart Speaker',pairTag:'Voice Interaction Design',year:'Flagship Project',title:'AVA Smart Speaker Interaction System',
scope:'Hardware–software integration design, requirements translation, animation production, cross-team coordination',collaborators:'PM · Frontend & backend engineers',
oneLiner:'An all-in-one AI voice butler for hotel rooms — from conversation design and multi-feature user flows to interaction animations, creating a consistent, intuitive hardware–software experience.',
blocks:[
{heading:'Background',type:'text',items:['An AI voice butler for hotel rooms. Guests can order room service, request amenities, transfer calls, start a meditation mode synced with the room’s lighting, and ask about the room and hotel facilities.']},
{heading:'Results at a Glance',pin:1,type:'cards',items:[{stat:'7',statUnit:'hotels in one month',title:'7 hotels renewed or upgraded within a month',text:'Within a month of the new call flow going live, 7 hotels renewed or upgraded to the new UI and call model, and newly onboarded hotels choose the latest UI.'},{stat:'+1',statUnit:'new hotel client',title:'Closed a new partnership',text:'Launching the Wellness meditation feature directly led to a partnership with that hotel client'}]},
{pin:1,type:'text-image',items:[{noImage:true,small:true,title:'UI refresh, now live',text:'Redesigned around information hierarchy and clearer wording. For example, alarm dates now read “Today” or “Thu, Sep 10” instead of “06/03 Mon”, matching the date formats guests from different countries are used to.',compare:[{label:'Dial pad',before:'slot-assets/ava-ba-dial-before.png',after:'slot-assets/ava-ba-dial-after.png'},{label:'In a call',before:'slot-assets/ava-ba-call-before.png',after:'slot-assets/ava-ba-call-after.webp'},{label:'Delivery service',before:'slot-assets/ava-ba-delivery-before.png',after:'slot-assets/ava-ba-delivery-after.png'},{label:'Clock',before:'slot-assets/ava-ba-clock-before.png',after:'slot-assets/ava-ba-clock-after.png'}]}]},
{heading:'Problems & Challenges',type:'text',items:['AVA faced two very different challenges. The first was systemic: requests kept arriving from clients, device specs, AI model updates and third-party integrations, so I needed an approach that could extend instead of being rebuilt each time. The second was sensory: a client wanted a relaxing meditation experience, which meant turning an abstract feeling into visuals, sound and lighting.','One called for systems thinking; the other for sensory judgment.']},
{heading:'Systematic Design Decisions',type:'text-image',items:[{imgId:'ai-butler-call-states',natural:true,title:'Upgrading the AI Call Flow',text:'Problem: the screen played the same animation in every state, so users couldn’t tell whether the device was still listening. They repeated themselves or waited anxiously.\n\nSolution: I defined each system state and how it looks. Listening shows a static icon so users can focus on speaking; an animated loading state appears only while the AI is processing. AI behavior became predictable.\n\nThe diagram below shows how the listening, thinking and responding states transition.'},{imgId:'ai-butler-phone-merge',natural:true,title:'Next: Merging with the Existing Phone Module',text:'When the conversation feature moved into the phone module, it had to merge with existing functions like calling other rooms and transferring to the front desk. I refreshed the interface with engineers and the PM, and the state system from the previous version carried over without redesign.'},{imgId:'ai-butler-phone-merge-r',natural:true},{imgId:'ai-butler-iot',title:'In-Room IoT Integration',text:'Every TV brand works differently: some need separate on and off buttons, others toggle with one, and Japanese models require choosing an input before a channel. I worked through each vendor’s logic with engineers and the PM before designing the controls.'}]},
{heading:'Ambient Experience Design',type:'text-image',items:[{noImage:true,title:'Wellness Meditation',text:'A single tap triggers synchronized animation, sound, and in-room lighting changes for an immersive, mind-and-body relaxation experience.'},{noImage:true,small:true,title:'My Role',text:'Worked with the PM to define and standardize several lighting and sound themes, setting the tone of the overall experience\nIndependently conceived and produced animations for each theme, aligning the rhythm of visuals, sound, and lighting'},{noImage:true,small:true,title:'Outcome / Takeaways',text:'It led directly to a partnership with the hotel. It also taught me that a good interface isn’t always a complete one: in meditation, the UI should step back and let animation, sound and light lead.'},{imgId:'ai-butler-wellness-video',ratio:'4/3'},{pairIds:['ai-butler-festive-anim','ai-butler-festive-anim-2','ai-butler-festive-anim-3','ai-butler-festive-anim-4'],title:'Holiday-Themed Animations',text:'I also produce holiday-themed animations for marketing, adding seasonal atmosphere to the room.'},{imgId:'ai-butler-home-custom',title:'Home Screen Customization',text:'One system, many brand looks: home screen colors, fonts and layout adjust per hotel, from understated luxury to fresh minimalism, with no redevelopment.'}]},
{heading:'Results',type:'text-image',items:[{noImage:true,title:'Hotel Feedback',text:'“Now housekeeping requests get a fast response, restaurant reservations are easy to arrange, and guest preferences are recorded automatically — all thanks to the leading AI technology of the Aiello Voice Assistant.” — M Social Hotel Phuket, Thailand.'}]},
{heading:'Reflection',type:'text',items:['Crafting one sensory experience and systematizing everyday needs look like opposite skills, but both answer the same question: what does the user actually need right now?','Next time, I would track how often guests repeat themselves or interrupt the device after launch, to measure how much the clearer states helped.']}
]},
{id:'aca-ai',highlight:'0% → 92% of phone orders completed by AI',coverRatio:'2/1',projectType:'UX Design · Data Analysis',timeline:'2026 – Now',platform:'Phone',timelineFirst:true,labels:['Voice Interaction Design','Conversation Flow Design'],tag:'AI Phone Agent',pairTag:'Conversation Flow Design',tag3:'Test Scenario Planning',year:'Flow Optimization',title:'AI Voice Agent for Hotel In-Room Dining',
scope:'Data analysis, requirements translation, VUI flow planning',collaborators:'PM · Backend engineers',
oneLiner:'I analyzed thousands of real phone calls, then broke down and rebuilt human agents’ ordering logic into service guidelines an AI can execute reliably — so every call sounds like it’s being handled by a seasoned agent.',
blocks:[
{heading:'Results at a Glance',pin:1,type:'cards',items:[
{compact:true,stat:'92%',statUnit:'orders completed by AI',title:'0% → 92% of phone orders completed by AI',text:'Room service is 16% of all calls, and the AI used to transfer every order to a human. In internal stress tests, 46 of 50 calls ended with a complete order.',noImage:true},
{compact:true,title:'Smoother conversations, faster delivery',text:'The AI asks fewer unnecessary questions, and engineers implement directly from the guidelines, shortening regression testing',noImage:true}
]},
{pin:1,type:'text-image',items:[{noImage:true,small:true,title:'Scenarios the AI agent now handles',text:'Five situations from real calls. Switch between them to compare the AI’s replies before and after the guidelines.',chat:{scenarios:[{label:'Menu questions',before:[{who:'guest',text:'Do you have Hainanese chicken rice on the menu?'},{who:'ai',text:'For menu information I need to transfer you to a staff member. Shall I transfer you?'}],after:[{who:'guest',text:'Do you have Hainanese chicken rice on the menu?'},{who:'ai',text:'Yes, we do! Would you like me to order one for you?'}]},{label:'Lookup failures',before:[{who:'guest',text:'I’d like to add a side of fries.'},{who:'ai',text:'Tool call failed.'}],after:[{who:'guest',text:'I’d like to add a side of fries.'},{who:'ai',text:'Sorry, I can’t find fries right now. Would you like to see our other snacks?'}]},{label:'Describing dishes',before:[{who:'guest',text:'Any dessert you’d recommend?'},{who:'ai',text:'I found tiramisu and brownies in the menu.'}],after:[{who:'guest',text:'Any dessert you’d recommend?'},{who:'ai',text:'Our tiramisu is a favorite, and we also have a warm brownie. Which would you like to try?'}]},{label:'No back-to-back questions',before:[{who:'guest',text:'I’d like a steak.'},{who:'ai',text:'How would you like it cooked? Which sauce? What’s your room number?'}],after:[{who:'guest',text:'I’d like a steak.'},{who:'ai',text:'Sure, one steak. How would you like it cooked?'}],note:'Anything still missing is collected once, at the confirmation checkpoint at the end.'},{label:'Special requests',before:[{who:'guest',text:'Can I get the pasta without garlic?'},{who:'ai',text:'I can’t answer that. Let me transfer you to a staff member.'}],after:[{who:'guest',text:'Can I get the pasta without garlic?'},{who:'ai',text:'I’ll note “no garlic” on your order. Or would you like to check with the kitchen directly?'}]}]}}]},
{heading:'Background',type:'text',title:'Phone ordering was the feature hotels cared about most — yet it still hadn’t been built',sideChart:[
{label:'Human agent request',pct:100,value:'27%',color:'#B0B0B4'},
{label:'In-room dining',pct:59,value:'16%',color:'#85B7EB',bold:true},
{label:'Laundry',pct:41,value:'11%',color:'#B0B0B4'},
{label:'Other',pct:41,value:'11%',color:'#B0B0B4'},
{label:'Amenities',pct:33,value:'9%',color:'#B0B0B4'},
{label:'Room Reservation',pct:33,value:'9%',color:'#B0B0B4'},
{label:'Technical Repair',pct:19,value:'5%',color:'#B0B0B4'},
{label:'Other Topic',pct:15,value:'4%',color:'#B0B0B4'},
{label:'Hotel Policy',pct:11,value:'3%',color:'#B0B0B4'},
{label:'F&B Facility',pct:7,value:'2%',color:'#B0B0B4'},
{label:'Transport&Travel',pct:4,value:'1%',color:'#B0B0B4'}
],items:['This is an AI voice agent built for the hospitality industry, designed to solve a structural problem: hotels have limited staff, yet must respond to guest requests 24 hours a day.','Call data showed phone ordering was the most requested service, ahead of laundry, amenities and maintenance, and it drives F&B revenue. But menus change by time of day, stock changes in real time and guests make custom requests, so ordering was left out of the first launch.','I led the conversation flow design, breaking down how human agents handle phone orders into a flow an AI can follow.']},
{heading:'Problems & Challenges',type:'bullets',items:['Too many scenarios: ordering had to become a flowchart developers could build.','Unclear limits: I had to know what the AI could handle before agreeing on scope with hotels.','Hard to verify: checking whether the AI followed the rules meant digging through system logs.','Concise vs. explicit: the AI needs clear rules, but longer guidelines confuse it.','Too much data: I needed a fast way to find the records that matter.']},
{heading:'Process',type:'text-image',items:[
{title:'Extracting an actionable flow from real calls',text:'With a data analyst, I used AI to analyze thousands of real call recordings and map the full ordering flow. Ordering isn’t linear, so I split it into a main flow and edge cases, then decided with the PM and engineers which cases the AI handles and which go to a human.',imgId:'aca-flow-1',natural:true},
{title:'Building team consensus, then aligning with hotels',text:'After the team agreed on the AI’s boundaries, we confirmed service principles with hotels. I turned them into a Policy document the AI agent reads, plus test scenarios to validate the flow.',imgId:'aca-flow-2',natural:true},
{title:'Applying VUI design principles to reduce cognitive load',text:'I followed NN/g’s voice interface (VUI) guidelines: voice has no screen to rescan, so information must come in small chunks. The AI gives only what the next step needs and confirms before going deeper. This became a baseline rule for every ordering flow.',imgId:'aca-flow-3',noImage:true},
{text:'I also wrote rules for moments when the AI didn’t sound like a professional agent:',noImage:true},
{title:'• Don’t read out system terms when a lookup fails',text:'The AI used to read out system error messages. Now it uses plain, reassuring language.',noImage:true},
{title:'• Describe dishes in a professional, hospitality-appropriate tone',text:'The AI used to open with system-like phrases such as “I see…”. Now it leads with the dish itself, like a hotel agent would.',noImage:true},
{title:'• Don’t ask follow-ups back-to-back when a guest skips a question',text:'The AI used to chase every skipped detail right away, which felt pushy. A confirmation checkpoint at the end now collects anything missing.',noImage:true},
{title:'• Don’t transfer to a human just because an answer can’t be found',text:'The AI used to transfer to a human whenever an answer wasn’t on the menu, adding work for staff. Now guests choose: add a note to the order and continue, or talk to a person.',noImage:true},
{text:'These weren’t one-off fixes. Every new issue goes through the same method:',noImage:true},
{title:'Turning discovered issues into guidelines',noImage:true},
{title:'• Categorize the issue first, then identify the root cause',text:'Is it the guideline, the data or the flow? A clear cause makes each change easy to explain to the team.',imgId:'aca-flow-4'},
{title:'• Write guidelines as Do / Don’t',text:'Explicit behavior rules leave less room for the AI to guess, and engineers can implement them directly.',noImage:true},
{title:'• Restructure the RAG knowledge base the AI queries',text:'Consolidate the scattered information hotels provide into a consistent structure, so the AI retrieves more accurately and answers more reliably.',noImage:true},
{title:'• Build a Claude Skill to speed up validation',text:'Tracing what an AI reply was based on used to take manual digging. I built a Skill that connects to Grafana and lists the MCP tools and knowledge base data used in a call, cutting validation to seconds.',imgId:'aca-flow-6',imgId2:'aca-flow-6b',natural:true}
]},
{heading:'Results & Impact',type:'text',items:['Conversations became smoother with fewer unnecessary questions, making calls easier for guests. Clear guidelines also made implementation easier and shortened regression testing.']},
{heading:'Reflection',type:'text',items:['Voice design has to start from real data. Many problems only show up when you read through real conversations, not through reasoning alone.']}
]},
{id:'guestweb',highlight:'SaaS product: AI-assisted research, design system, and admin back office',projectType:'UX Research · Design System · Web UI Design',platform:'Web (guest-facing in-room interface + hotel admin back office)',timeline:'2024 – Now',coverHeadline:'One system, endless styles',labels:['UX Research','Design System','Web UI Design'],tag:'Multi-brand Website',pairTag:'Content Management System',year:'Systems Thinking',title:'GuestWeb Hotel Digital Concierge',
scope:'Design system lead · Requirements translation · Cross-team coordination',collaborators:'PM · Frontend & backend engineers · Hotel brand contacts',
oneLiner:'A hotel-branded front desk web page guests open by scanning a QR code, managed by hotels through a SaaS back office — a digital concierge system where multiple brands share one architecture while each keeps its own style.',
blocks:[
{heading:'Background',type:'text',title:'This system lets every hotel quickly launch a service website that feels “built for their brand” — while all of them run on one shared, maintained architecture',items:['Guests scan an in-room QR code to open the hotel’s own front desk page. From pre-arrival to check-out, they can look up information, order food, request deliveries, book rides and arrange laundry, without downloading an app. Hotels manage it all through a SaaS back office.','Every hotel wants a page that fits its brand and can go live without engineers. So I designed flexible templates and components, with a back office simple enough for hotels to customize themselves.']},
{heading:'Results at a Glance',pin:1,type:'cards',items:[
{compact:true,stat:'NT$270K',statUnit:'monthly F&B revenue, one hotel',title:'Revenue growth',noImage:true},
{compact:true,stat:'384',statUnit:'calls saved in a month',title:'Staff time saved',noImage:true},
{compact:true,title:'Development cost efficiency',text:'New brands launch without building a new system; the shared architecture greatly reduces maintenance and scaling costs',noImage:true}
]},
{pin:1,type:'text-image',items:[{noImage:true,small:true,title:'Back office and guest page, live',text:'The final design: a back office hotels can edit freely and understand at a glance, with the guest page updating to match.',media:'slot-assets/guestweb-builder.gif',mediaRatio:'1200/721'}]},
{heading:'Problems & Challenges',type:'bullets',items:['Widely varying style expectations: Japanese hotels value complete information, luxury brands value atmosphere and whitespace — every standard differs','Drawing the line on customization: the architecture must be flexible enough, without spiraling into runaway maintenance costs','Complex multi-role scenarios: front desk, housekeeping, and F&B staff work differently, requiring interviews and competitive research to reflect real needs']},
{heading:'A Real Case Behind the Challenge',type:'text-image',items:[{noImage:true,title:'Assumption',text:'The initial MVP had a single default interface with a middle-ground text-to-image ratio, targeting the needs of small business hotels.'},{imgId:'guestweb-case-issue',ratio:'1/1',title:'What We Found',text:'As we added clients, we found opposite expectations: luxury hotels wanted full-bleed images with little text, while Japanese hotels wanted dense, detailed text to reassure guests.'},{noImage:true,title:'The Pivot',text:'One default style couldn’t serve both, so we moved from one fixed ratio to a design system where each brand sets its own text-to-image ratio.'}]},
{heading:'Implementation After the Pivot',type:'text-image',items:[{imgId:'guestweb-case-impl',title:'A Design System with Configurable Text-to-Image Ratios',ratio:'4/3',text:'I turned the text-to-image ratio into configurable specs instead of hard-coding it, so one system serves both atmosphere-driven and information-driven hotels. Below are proposals for different hotels and their spec documents:'},{noImage:true,title:'Free Layout vs. Grid System: Finding the Balance with Engineering',text:'I first wanted Webflow-style free layout, but engineers noted that calculating widths on the fly would be costly to maintain. I switched to a grid with a few fixed sizes, and the back office shows how much space is left. Free layout is Webflow’s selling point and worth heavy investment; for an internal tool with few page types, giving up a little flexibility for lower maintenance was the better trade. Hotels found it flexible enough, engineering agreed, and it shipped.'}]},
{type:'text-image',items:[{imgId:'guestweb-3-1',ratio:'1.9/1',title:'Systematized Flexibility: Designing the Boundaries of Customization',text:'Hotels adjust layout, colors and the chatbot greeting themselves in the back office. Components share one spec and can be swapped independently, so more customization doesn’t mean more maintenance.'},
{imgId:'guestweb-3-1-r',natural:true}]},
{heading:'My Role & Process',type:'text-image',items:[
{noImage:true,title:'Exploring and Distilling Real Needs',text:'I interviewed hotel staff and observed front desk, housekeeping and F&B teams on site. I also used AI to build interactive prototypes quickly, for interviews and internal usability tests, so assumptions were validated early.'},
{pairIds:['guestweb-3-0b','guestweb-3-0c']},
{imgId:'guestweb-3-0'},
{imgId:'guestweb-3-0d',natural:true,caption:'Using an AI-built mock website to test users’ mental models when operating the back-office system'},
{noImage:true,title:'Two Opposite Mental Models',text:'For the CMS, interviews and usability tests showed people want to see the whole page first, so the back office opens on a high-fidelity preview, then lets users drill into details.\n\nFor the menu back office, the same research showed the opposite: staff build a product library first, then add items to menus one by one — small to large, not large to small.'},
{imgId:'guestweb-mental-model',ratio:'4/3',title:'The Solution',text:'So I gave the CMS and menu management different structures and workflows. The same users think differently about different tasks, and design should follow the task.'},
{imgId:'guestweb-3-2',title:'Tokenizing the Back-Office Design System into an AI Skill',text:'I turned the specs into a format AI can read, so it generates on-spec design proposals for validation instead of building each from scratch. The output goes straight into engineering discussions and usability tests, shortening the validation cycle.'}
]},
{heading:'Results & Impact',type:'text-image',items:[
{noImage:true,title:'Results by Hotel',text:'Holiday Inn: about NT$270K in monthly F&B revenue and 450 orders after launch.\niHotel: about NT$160K in monthly revenue and 490 orders.\nHotel Clover saved 384 phone calls in one month, while receiving 204 proactive guest inquiries.'},
{noImage:true,title:'Hotel Feedback',text:'“This channel lets us engage with guests in a better way — not only keeping them up to date on the latest offers in real time, but also ensuring they never miss any information, for a smoother, more engaging stay.” — Holiday Inn & Suites Saigon Airport.\n“Since we started working together, our F&B revenue has grown 30× compared to the same period, and the Aiello Voice Assistant is the best low-friction ordering tool on the market today.” — iHotel.'}
]},
{heading:'Reflection',type:'text',items:['Custom home pages and menus also have to match each hotel’s ordering system data. Design isn’t only about how screens look; the data underneath has to line up.']},
{type:'text-image',items:[{imgId:'guestweb-3-1b'}]},
]},
{id:'tms',tag:'Research-Driven Product Design',year:'Research Methods',title:'TMS Portal / StaffApp',
scope:'Visited hotel sites and interviewed staff across departments, translating insights into interface design decisions',collaborators:'Housekeeping, Front Desk, Maintenance, Product Team',
oneLiner:'A highly customizable smart task platform that automatically assigns tasks based on how each hotel operates, boosting staff efficiency, streamlining operations, and delivering actionable data insights.',
blocks:[
{heading:'Background',type:'text',items:['TMS helps hotels manage tasks across departments, automatically assigning them to the right staff based on workflows. It’s also the back-office system hotels use to configure in-room TV menu content, in-house push notifications, guest wake-up calls, and more.']},
{heading:'Problems & Challenges',type:'text',items:['Different hotels focus on different tasks. The core challenge was letting staff in different roles quickly find what’s useful to them on the same screen, without making it cluttered.']},
{heading:'Research Methods',type:'bullets',items:['Visited hotel service areas in person to understand how departments like housekeeping, front desk, and maintenance work together, and interviewed hotel staff about their day-to-day working habits.','Synthesized interview findings into usable insights, clarifying each role’s responsibilities and the information they care about most, as a basis for design decisions.','Built a reusable UI component library to rapidly create web prototypes for user testing.']},
{heading:'My Role & Process',type:'text',items:['Organized interview findings into information the team could use, and kept referencing them in subsequent design decisions.']},
{heading:'Solution',type:'text',items:['Adjusted the level of detail shown in the task list, and redesigned the room status overview using the terminology and status-light colors housekeeping staff are familiar with, making information clearer at a glance.']},
{heading:'Results & Impact',type:'text',items:['Improved screen presentation reduced mistaps when staff report task status; a reworked task management view sped up managers’ shift scheduling and cleaning assignments.']},
{heading:'Reflection',type:'text',items:['Only through interviews and on-site visits can you truly understand how users work and solve problems effectively. At the same time, hotel managers and frontline staff often care about different things, and design needs to find a balance between the two.']}
]},
{id:'nexus',highlight:'Shipped in 2021',dark:true,coverNatural:true,coverHeadline:'Readable at a glance, built to look the part.',projectType:'UI Design · Hardware–Software Integration',timeline:'2020',platform:'Streaming controller panel + desktop software',timelineFirst:true,labels:['UI Design','Hardware–Software Integration','Motion Design'],title:'Live Streamer NEXUS',
oneLiner:'A streaming controller and its companion software. Starting from how streamers actually use it mid-broadcast, I built a visual system that makes every state readable at a glance on a small screen, without giving up the bold esports look the product needed.',
scope:'Dynamic UI components for the hardware panel and desktop software, boot animation, LED lighting scripts, icon library, UI string translation',
blocks:[
{heading:'Background',type:'text',title:'Streamers glance at the controller. They don’t study it.',items:['NEXUS is AVerMedia’s streaming software, paired with the Live Streamer NEXUS controller. Streamers use its touchscreen and knobs to switch capture sources, mix audio and trigger hotkeys.','Mid-stream, attention is on the game and the audience; the controller gets only a glance. So every button has to show what it does and whether it’s on, in that split second.']},
{type:'cards',items:[{title:'Before',text:'Mid-stream, streamers often had to open several programs and adjust audio levels and aspect ratios'},{title:'With NEXUS',text:'Preset multiple streaming scenes, then swipe the controller’s screen to switch between them instantly'}]},
{heading:'Project at a Glance',pin:1,type:'cards',items:[
{compact:true,noImage:true,stat:'2021',statUnit:'mass-produced',title:'Shipped in 2021',text:'Launched as a mass-produced product: AVerMedia Live Streamer NEXUS (model AX310).'},
{compact:true,noImage:true,title:'State readable at a glance',text:'Hotkeys pair each app’s brand color with motion: on is full color and animated, off dims to a dark tone.'},
{compact:true,noImage:true,title:'One look across hardware and software',text:'The same components run on the controller’s touchscreen and in the desktop app, backed by an icon library with five interaction states.'},
{compact:true,noImage:true,title:'A complete visual asset system',text:'A boot animation with a millisecond-timed LED script, custom hotkey icons, and an app icon in 9 sizes from 16 to 1024 px.'}
]},
{heading:'Problems & Challenges',type:'bullets',items:['A glance, not a gaze: streamers look down for a split second mid-stream, so state has to register instantly','A small screen: on the controller’s touchscreen, subtle changes in an icon’s shape are easy to miss','Same function, different channels: once NEXUS integrated platforms like OBS and Twitch, buttons with the same function but for different channels could appear on the same page, and had to be told apart at a glance','Two displays, one component: the same UI appears on the hardware touchscreen and in the desktop software','Clarity without losing flair: this is a product for streamers and gamers, so it also has to look bold and polished']},
{heading:'Design Decisions',type:'text-image',items:[
{title:'Designing for a glance: from text labels to color and motion',text:'The original icons marked state with tiny ON / OFF text, easy to miss on a small screen. After adding OBS and Twitch, same-function buttons for different channels also had to be told apart.\n\nMy first version used color families for channels and built the state into the icon. My manager and fellow designers felt the contrast should be stronger for quick mid-stream use.\n\nIn the final version, each hotkey uses its app’s brand color: full color and animated when on, dimmed when off. The state reads even from the corner of the eye.',noImage:true,iconCols:5,iconGrid:['slot-assets/nexus-hotkey-on-1-mixer.gif','slot-assets/nexus-hotkey-on-2-share.gif','slot-assets/nexus-hotkey-on-3-layers.gif','slot-assets/nexus-hotkey-on-4-camera.gif','slot-assets/nexus-hotkey-on-5-record.gif','slot-assets/nexus-hotkey-off-1-mixer.png','slot-assets/nexus-hotkey-off-2-layout.png','slot-assets/nexus-hotkey-off-3-layers.png','slot-assets/nexus-hotkey-off-4-store.png','slot-assets/nexus-hotkey-off-5-record.png','slot-assets/nexus-hotkey-blue-1-folder.gif','slot-assets/nexus-hotkey-blue-2-mixer.gif','slot-assets/nexus-hotkey-blue-3-sound.gif','slot-assets/nexus-hotkey-blue-4-seat.gif','slot-assets/nexus-hotkey-blue-5-play.gif']},
{title:'• Customizable, without breaking the system',text:'In NEXUS’s online editor, streamers can set their own hotkey backgrounds and images. I drew icon sets in several styles so personalized layouts still look polished.',noImage:true,iconCols:5,iconGrid:['slot-assets/nexus-custom-1-guitar.png','slot-assets/nexus-custom-2-award.png','slot-assets/nexus-custom-3-kaomoji.png','slot-assets/nexus-custom-4-moon.png','slot-assets/nexus-custom-5-device.png']},
{title:'One visual language across hardware and software',text:'The desktop app uses a dark base to match the controller. I drew a clean line-icon library and specified five interaction states: Normal, Mouse over, Click, Disable and Focus.',imgId:'nexus-icon-library',natural:true},
{title:'Visual flair that carries the brand: boot animation and lighting',text:'Clarity sets the rules, but the product should also excite at power-on. With a flashy esports concept, I animated the AVerMedia logo for the boot screen and designed LED effects that flash in sync.',imgId:'nexus-boot',natural:true},
{title:'• Lighting scripts timed to the millisecond',text:'The lighting changes fast, so I scripted each pattern precisely, millisecond by millisecond.',imgId:'nexus-light-script',natural:true},
{title:'• App icon',text:'Based on the controller’s knobs and the software’s signature orange, I drew the app icon in 9 sizes, from 16 to 1024 px.',imgId:'nexus-app-icon',natural:true}
]},
{heading:'Final Product',pin:2,type:'text-image',items:[{imgId:'nexus-final',natural:true}]},
{heading:'Reflection',type:'text',items:['NEXUS taught me to design hardware and software as one experience. The lights, the touchscreen and the desktop settings all answer one question: what does the streamer need to know right now?','If I did it again, I would test hotkeys in real streams, not only design reviews, to confirm the dimmed off state stays readable under real lighting.']}
]},
{id:'1177pay',highlight:'Consumer app improvements: bills, donations, and card binding',coverNatural:true,projectType:'UI Design · B2C Mobile Payment',timeline:'2021 – 2023',platform:'Mobile App',timelineFirst:true,coverHeadline:'Making bill payment quick and easy, starting from the very first payment.',labels:['UI Design','B2C Mobile Payment'],title:'1177PAY Mobile Payment App',
scope:'Bill details, donation page, card-binding flow, widget, loading animation, flowcharts, Design Guideline maintenance',collaborators:'PO · Other designers',
blocks:[
{heading:'Background',type:'text',items:['1177PAY is a mobile payment app. Users link credit cards, bank accounts and e-invoice barcodes to pay quickly, and get bills and payment confirmations through push notifications.','Goal: make paying bills fast, and turn first-time users of the company’s payment services into loyal app members.','Several designers worked on the app. I owned bill details, the donation page, the card-binding flow, and details like the widget and loading animation.']},
{heading:'Project at a Glance',pin:1,type:'cards',items:[
{compact:true,noImage:true,title:'Bills and donations',text:'Reordered the information in bill details, and redesigned the main screen for browsing charities on the donation page.'},
{compact:true,noImage:true,title:'Easier card binding',text:'Showed each card’s issuing bank logo, and improved the camera screen for scanning a credit card and filling in its details automatically.'},
{compact:true,noImage:true,title:'Visual details',text:'A widget in light and dark mode, a loading animation made in After Effects, and the App Store screenshots.'}
]},
{heading:'Problems & Challenges',type:'bullets',items:['Converting first-time users: many people meet 1177PAY through the company’s payment services rather than the app store, so the app has to show its value right away.','Complex payment flows: payments involve many checkpoints and branches, which have to be documented clearly enough for engineers to build.','Trust when adding a card: linking a credit card is a sensitive step, so users need to recognize their card and understand what the camera is doing.','Keeping a growing product consistent: as new features are added, the Design Guideline has to stay up to date so every screen still feels like the same product.']},
{heading:'Design Decisions',type:'text-image',items:[
{title:'Turning requirements into screens',text:'Working with the PO, I designed screens from the wireframes and wrote the design specifications.',imgId:'pay-screens',natural:true},
{title:'• Making card binding easier to trust',text:'Each card shows its bank’s logo so users recognize it instantly. I also made the card-scanning camera screen easier to understand and use.',noImage:true},
{title:'• Bill details and donations',text:'I reordered the information in bill details, and redesigned the main screen where users browse charities on the donation page.',noImage:true},
{title:'• Widget design',text:'Designed in both light and dark mode.',imgId:'pay-widget',natural:true},
{title:'• Loading motion design',text:'Inspired by a wallet’s snap button opening, I created the loading animation in After Effects.',imgId:'pay-loading',natural:true},
{title:'• Color palette',text:'Built on the blue of the company’s corporate identity, paired with grays and whites for a clean, trustworthy feel.',imgId:'pay-color',natural:true},
{title:'Flowcharts',text:'From the finished screens, I drew flowcharts marking checkpoints and screen transitions.',imgId:'pay-flow',natural:true},
{title:'Design handoff',text:'I delivered the designs and sliced assets through Sketch and Zeplin.',imgId:'pay-handoff',natural:true}
]},
{heading:'Results',type:'text',items:['I delivered bill details, the donation page, the card-binding flow, the widget, the loading animation, flowcharts and App Store screenshots, and kept the Design Guideline current.']},
{heading:'Reflection',type:'text',items:['In a payment product, trust is built in the details: a familiar bank logo on each card, a clear state at every checkpoint, and reminders that arrive before users have to think about their bills.']},
{heading:'Final Product',pin:2,type:'text-image',items:[{imgId:'pay-feature-pay',natural:true},{imgId:'pay-feature-push',imgId2:'pay-feature-scan',natural:true}]}
]},
{id:'17backstage',highlight:'Built a design system; proposal adopted company-wide',coverNatural:true,projectType:'UI Design · B2B Back Office',timeline:'2021 – 2023',platform:'Web back office',timelineFirst:true,coverHeadline:'Turning a templated back office into a clear, consistent system for small merchants.',labels:['UI Design','B2B Back Office','Redesign'],title:'1177 Tech Merchant Back Office',
scope:'Redesign proposal, layout and interaction design, Design Guideline, wireframes, mockups and handoff',collaborators:'Company leadership · Product manager · Frontend engineers',
blocks:[
{heading:'Background',type:'text',title:'Small merchants needed a simpler way to accept payments',items:['1177 Tech provides third-party payment collection, letting merchants accept credit cards, convenience-store payments and virtual-account transfers on their own online store platforms.','The back office was an MVP for small merchants and charities that need to collect payments but don’t want to apply for a card terminal or LINE Pay. The goal: quick to sign up, intuitive to use.','The first version was built on a template, and leadership found it hard to use. As the company’s only UI designer, I led the redesign.']},
{heading:'Project at a Glance',pin:1,type:'cards',items:[
{compact:true,noImage:true,title:'Proposal adopted company-wide',text:'Leadership chose my redesign proposal and asked me to apply its design guideline to every product line in the company.'},
{compact:true,noImage:true,stat:'1',statUnit:'designer, end to end',title:'The only designer, end to end',text:'From the proposal and the Design Guideline to wireframes, mockups and handoff, I designed the whole system.'},
{compact:true,noImage:true,stat:'3',statUnit:'layout improvements',title:'Three layout improvements',text:'A top menu set apart from content, detail pages shown as popups, and a collapsible step bar for long forms.'}
]},
{heading:'Problems & Challenges',type:'bullets',items:['Too much information: lots of data, and users need to find features fast.','Unclear hierarchy: a vertical menu next to vertical data lists looked like the same level.','Endless scrolling: details were listed one per line, making pages very long while the right half of the screen sat mostly empty.','Cramped forms: the step bar on the left of form pages squeezed the width of the form itself.','Easy-to-miss errors: errors in the application form were shown only as text, so users could easily overlook them.']},
{heading:'Design Decisions',type:'text-image',items:[
{title:'Leading with the reasoning: a proposal built around how people read',text:'Instead of just new screens, I presented a deck explaining why each component sits where it does: following reading order, guiding the eye, and making risky actions clear. Leadership chose it, and it became the basis of the new Design Guideline.',noImage:true},
{title:'Reorganizing the screen layout',text:'The old left-side menu looked too similar to the vertical data lists. I moved it to the top, with a shadow and a different background to separate it from the content.\n\nI considered keeping the side menu, but with so many items it would take too much space and pull focus from the content.',imgId:'bs-layout',natural:true},
{title:'Rearranging detail pages, so users no longer scroll endlessly',text:'Detail pages listed one item per line, making pages long with an empty right half. We split information into columns with wrapping rules by field length, and turned details into a popup so users can compare records easily.',imgId:'bs-detail',natural:true},
{title:'Consolidating form pages',text:'The step bar on the left squeezed the form. I made it expandable and collapsible, so users jump straight to the section they need.',imgId:'bs-form',natural:true},
{title:'• Earlier, clearer error messages',text:'Errors used to be text only. Now users are warned before moving on, with an icon, and each field shows its progress and state.',imgId:'bs-form-hints',natural:true},
{title:'A new Design Guideline',text:'From the proposal, I built a shared component library to keep systems consistent. Leadership applied it to every product line, and the visual designer used it for marketing too.',pairIds:['bs-guide-input','bs-guide-dropdown','bs-guide-icon-btn','bs-guide-font']},
{title:'Discussing wireframes',text:'I used wireframes to discuss component usage and screen layouts with the product manager.',imgId:'bs-wireframe',natural:true},
{title:'Building mockups',text:'I designed the screens in Sketch and uploaded them to Zeplin for handoff to the frontend engineers.',noImage:true}
]},
{heading:'Final Product',pin:2,type:'text-image',items:[{imgId:'bs-final-1',natural:true},{imgId:'bs-final-2',natural:true},{imgId:'bs-final-3',natural:true},{imgId:'bs-final-4',natural:true},{imgId:'bs-final-5',natural:true}]},
{heading:'Results',type:'text',items:['The back office was still an MVP, so the impact was internal: leadership adopted my proposal, the Design Guideline went company-wide, and the visual designer used it for marketing.']},
{heading:'Reflection',type:'text',items:['A redesign wins on its reasoning, not just its screens. Explaining layout through reading order, visual flow and risk is what convinced leadership, and turned one redesign into a company-wide guideline.']}
]}
];
// Page variant, picked by URL: ?focus=ai leads with the AI voice work; ?focus=hardware leads with
// hardware–software work (?focus=automotive is the same with a motion-focused tagline); no param = default site (older ?focus=fintech links land here too).
// pairs:true lays every card out two per row instead of making the first card full width. aboutIntro / career (keyed by company) override the About page copy.
window.SITE_VARIANT=(()=>{
const focus=new URLSearchParams(window.location.search).get('focus');
if(focus==='hardware'||focus==='automotive'){
const hw={
order:['ai-butler','nexus','guestweb','aca-ai'],
pairs:true,
aboutIntro:'UI/UX designer with 5 years of experience, focused on products where hardware and software meet: from a live-streaming controller’s touchscreen and lighting to an AI smart speaker in hotel rooms. I start from the device’s environment, the context it is used in and the people who use it, then turn engineering constraints into clear, scalable design systems.',
career:{'Aiello':'Designing the AVA in-room smart speaker’s on-device interface, AI voice conversation experience and IoT controls (TV, lighting), plus AI phone ordering and hospitality SaaS products','AVerMedia':'Design internship | Live Streamer NEXUS controller: dynamic UI for the touchscreen and desktop software, boot animation, LED lighting scripts, icon library and app icon'},
headline:'Clarity between\npeople and devices.',
tagline:'Luna・UI/UX Designer・Hardware–Software Experiences',
resumeUrl:'https://drive.google.com/drive/folders/1U047kGSj6b7uZfmoTVgLbatRQR5mA4kY?usp=sharing'
};
// ?focus=automotive: the hardware variant with a motion-focused tagline, for in-vehicle / embedded UI roles.
return focus==='automotive'?{...hw,order:hw.order.concat(['17backstage','1177pay']),resumeUrl:'https://drive.google.com/drive/folders/1AvHO931eBC_5MsxLfNGtAgOee26VIhp2?usp=sharing',tagline:'Luna・UI/UX Designer・Hardware–Software UI & Motion'}:hw;
}
if(focus==='ai') return {
order:['aca-ai','ai-butler','guestweb','17backstage','1177pay'],
headline:'Designing AI that\nlistens, then acts.',
tagline:'Luna・UI/UX Designer・Conversational AI & Smart Devices',
resumeUrl:'https://drive.google.com/drive/folders/1kColvmaOikbEV8f8Nej0tayngMJpFT3f?usp=sharing'
};
return {
order:['guestweb','aca-ai','ai-butler','17backstage','1177pay'],
headline:'Clarity between\npeople and AI.',
tagline:'Luna・UI/UX Designer・AI SaaS Products',
resumeUrl:'https://drive.google.com/drive/folders/1XALJ8GZUo-nuZVn3wBFxr7idXlIw1IAG?usp=sharing'
};
})();
