window.PROJECTS_DATA=[
{id:'ai-butler',highlight:'7 hotels renewed or upgraded within a month',coverNatural:true,projectType:'Hardware–Software Integration · Interaction Design',timeline:'2023 – Now',platform:'Android App',timelineFirst:true,coverHeadline:'From a single sensory experience to a scalable system.',labels:['Hardware–Software Integration','Interaction Design'],tag:'Smart Speaker',pairTag:'Voice Interaction Design',year:'Flagship Project',title:'AVA Smart Speaker Interaction System',
scope:'Hardware–software integration design, requirements translation, animation production, cross-team coordination',collaborators:'PM · Frontend & backend engineers',
oneLiner:'An all-in-one AI voice butler for hotel rooms — from conversation design and multi-feature user flows to interaction animations, creating a consistent, intuitive hardware–software experience.',
blocks:[
{heading:'Background',type:'text',items:['An AI voice butler built for the hospitality industry, helping hotels build a smart brand image while improving guest satisfaction, operational efficiency, and revenue. Features include in-room dining, amenity delivery, call transfer, a meditation mode synced with in-room lighting, and Q&A about room equipment and hotel facilities.']},
{heading:'Results at a Glance',type:'cards',items:[{title:'7 hotels renewed or upgraded within a month',text:'Within a month of the AI call flow upgrade going live, 7 hotels had confirmed they would renew or upgrade to the new UI and the new call model, and newly onboarded hotels proactively choose the latest UI — a sign of sustained client trust in the system'},{title:'Closed a new partnership',text:'Launching the Wellness meditation feature directly led to a partnership with that hotel client'}]},
{heading:'Problems & Challenges',type:'text',items:['After AVA launched, the challenges it faced fell into two completely different categories. The first was systemic: requirements kept coming from different sources — client customization requests, evolving device specs, AI model iterations, and cross-vendor integrations — each with different conditions. Redesigning the logic every time wasn’t an option; I needed an approach that could be extended rather than rebuilt. The second was emotional: the client wanted to enhance the sensory side of their guests’ stay and asked for a relaxing meditation experience. This wasn’t an efficiency problem, but a question of how to translate an abstract “feeling” into concrete visual, sound, and lighting design.','These two challenges tested different abilities — the first called for systems abstraction, the second for judgment in translating the senses.']},
{heading:'Systematic Design Decisions',type:'text-image',items:[{imgId:'ai-butler-call-states',natural:true,title:'Upgrading the AI Call Flow',text:'In the original version, the screen played the same animation no matter what state the system was in. In reality, the device might already have stopped listening, or be processing a request that couldn’t be interrupted, so what users expected and what the device was actually doing could drift apart. That led to repeated speaking or anxious waiting.\n\nTo close this gap, I defined each system state separately and set rules for how each one looks. While listening, the screen shows a static icon, so users can focus on speaking without an animation pulling their attention. Only when the system is processing the conversation does an animated loading state appear, easing the anxiety of waiting. AI behavior that used to be opaque became predictable and perceivable.\n\nThe diagram below shows the transition logic between the listening, thinking, and responding states, along with the corresponding visual and interaction changes.'},{imgId:'ai-butler-phone-merge',natural:true,title:'Next: Merging with the Existing Phone Module',text:'As the conversation-processing model changed, the entire conversation feature moved into the phone module and had to be merged with existing phone functions (calling other rooms, transferring to a live front desk agent). I worked with engineers and the PM on the architecture changes and implementation, while refreshing the overall interface — and the system states and micro-interaction logic defined in the previous version carried straight over to the new architecture without redesign, proving that the state system could persist across versions.'},{imgId:'ai-butler-phone-merge-r',natural:true},{imgId:'ai-butler-iot',title:'In-Room IoT Integration',text:'Control logic varies dramatically between TV manufacturers: some map power on and off to separate codes, requiring two buttons; others toggle with a single button. On top of that, Japanese specs require selecting an input source before choosing a channel. To reflect these differences accurately, I held intensive meetings with engineers and the PM to clarify each vendor’s technical logic, making sure I fully understood the underlying constraints before designing the corresponding interface.'}]},
{heading:'Ambient Experience Design',type:'text-image',items:[{noImage:true,title:'Wellness Meditation',text:'A single tap triggers synchronized animation, sound, and in-room lighting changes for an immersive, mind-and-body relaxation experience.'},{noImage:true,small:true,title:'My Role',text:'Worked with the PM to define and standardize several lighting and sound themes, setting the tone of the overall experience\nIndependently conceived and produced animations for each theme, aligning the rhythm of visuals, sound, and lighting'},{noImage:true,small:true,title:'Outcome / Takeaways',text:'This directly led to a partnership with the hotel client. The project also taught me something that ran counter to my past experience: most features aim for complete information and a clear interface, but in a meditation context users need very little focus — the interface should be as minimal as possible and recede into the background, letting animation, sound, and lighting take center stage. It made me rethink what a “good interface” really means.'},{imgId:'ai-butler-wellness-video',ratio:'4/3'},{pairIds:['ai-butler-festive-anim','ai-butler-festive-anim-2','ai-butler-festive-anim-3','ai-butler-festive-anim-4'],title:'Holiday-Themed Animations',text:'Beyond Wellness, I continuously produced holiday-themed interactive animations for marketing needs, adding seasonal atmosphere to the in-room experience.'},{imgId:'ai-butler-home-custom',title:'Home Screen Customization',text:'The same system presents strikingly different visual styles depending on each hotel’s brand — from understated luxury to fresh minimalism. Home screen colors, typography, and layout are all flexibly adjustable, with no need to redevelop for each brand.'}]},
{heading:'Results',type:'text-image',items:[{noImage:true,title:'Hotel Feedback',text:'“Now housekeeping requests get a fast response, restaurant reservations are easy to arrange, and guest preferences are recorded automatically — all thanks to the leading AI technology of the Aiello Voice Assistant.” — M Social Hotel Phuket, Thailand.'}]},
{heading:'Reflection',type:'text',items:['From meticulously crafting a single sensory experience to using systems thinking to cover ever-changing everyday needs — these two seemingly opposite abilities share one thing: both answer the same question. What interface does the user truly need right now, rather than a default standard answer?','Looking back, I would also track data after the redesigned call flow went live, such as how often guests repeat themselves or interrupt the device, to measure how much the clearer states actually closed the gap.']}
]},
{id:'aca-ai',highlight:'0% → 92% of phone orders completed by AI',coverRatio:'2/1',projectType:'UX Design · Data Analysis',timeline:'2026 – Now',platform:'Phone',timelineFirst:true,labels:['Voice Interaction Design','Conversation Flow Design'],tag:'AI Phone Agent',pairTag:'Conversation Flow Design',tag3:'Test Scenario Planning',year:'Flow Optimization',title:'AI Voice Agent for Hotel In-Room Dining',
scope:'Data analysis, requirements translation, VUI flow planning',collaborators:'PM · Backend engineers',
oneLiner:'I analyzed thousands of real phone calls, then broke down and rebuilt human agents’ ordering logic into service guidelines an AI can execute reliably — so every call sounds like it’s being handled by a seasoned agent.',
blocks:[
{heading:'Results at a Glance',type:'cards',items:[
{compact:true,title:'0% → 92% of phone orders completed by AI',text:'In-room dining makes up 16% of all calls, and before, AI couldn’t take orders at all — every order call was transferred to a human. In internal stress testing, 46 of 50 calls ended with a complete order, no human needed.',noImage:true},
{compact:true,title:'Smoother conversations, faster delivery',text:'The AI asks fewer unnecessary questions, and engineers implement directly from the guidelines, shortening regression testing',noImage:true}
]},
{heading:'Background',type:'text',title:'Phone ordering was the feature hotels cared about most — yet it still hadn’t been built',sideChart:[
{label:'Human agent request',pct:100,value:'27%',color:'#B0B0B4'},
{label:'In-room dining',pct:59,value:'16%',color:'#85B7EB',bold:true},
{label:'Laundry',pct:41,value:'11%',color:'#B0B0B4'},
{label:'Other',pct:41,value:'11%',color:'#B0B0B4'},
{label:'Amenities',pct:33,value:'9%',color:'#B0B0B4'},
{label:'Room Reservation',pct:33,value:'9%',color:'#B0B0B4'},
{label:'Technical Repair',pct:19,value:'5%',color:'#B0B0B4'},
{label:'Other Topic',pct:15,value:'4%',color:'#B0B0B4'},
{label:'Hotel Policy',pct:11,value:'3%',color:'#B0B0B4'},
{label:'F&B Facility',pct:7,value:'2%',color:'#B0B0B4'},
{label:'Transport&Travel',pct:4,value:'1%',color:'#B0B0B4'}
],items:['This is an AI voice agent built for the hospitality industry, designed to solve a structural problem: hotels have limited staff, yet must respond to guest requests 24 hours a day.','After launch, back-office call statistics revealed a clear signal: excluding transfers to human agents, phone ordering was the single highest-volume service request — above laundry, amenities, and maintenance. Ordering also directly drives a hotel’s F&B revenue, making it an area hotels care about especially. But ordering involves time-based menu switching, real-time inventory, and custom requests, making it far more complex than other services, so it was left out of the initial launch.','To close this obvious service gap, as the project’s designer I led the AI conversation flow design. My strategy was to systematically break down the logic human agents use for everyday phone orders into a service flow an AI could also execute.']},
{heading:'Problems & Challenges',type:'bullets',items:['Ordering involves so many scenarios that mapping them into a flowchart developers could understand and build was no easy task.','I first had to understand the limits of the AI’s capabilities before defining a reasonable scope of service and reaching agreement with hotels.','I had to go back through system logs to confirm what the AI based its replies on, in order to judge whether the guidelines were actually being followed.','AI responses are inherently uncertain and need clear rules — but the longer the guidelines, the more easily the AI gets confused. I had to strike a balance between “concise” and “explicit.”','The monitoring system holds a huge volume of data, so I needed a way to quickly filter down to the records that actually mattered.']},
{heading:'Process',type:'text-image',items:[
{title:'Extracting an actionable flow from real calls',text:'Working with a data analyst, I obtained thousands of real call recordings and used AI to speed up the analysis, mapping out the complete flow phone ordering should follow. Ordering isn’t linear like typical UI, so after several attempts I split the flow into two layers — a “main flow” and “edge cases” — and turned it into an easy-to-read flowchart. I brought it to the PM and engineers to decide together which scenarios the AI could handle on its own and which had to be transferred to a human.',imgId:'aca-flow-1',natural:true},
{title:'Building team consensus, then aligning with hotels',text:'Once the team agreed internally on the AI’s service boundaries, we discussed service principles with hotels. After confirming the direction, I translated those principles into design guidelines the AI could understand and follow, wrote them into a Policy document for the AI Agent to read, and compiled a set of test scenarios to quickly validate whether the new flow worked.',imgId:'aca-flow-2',natural:true},
{title:'Applying VUI design principles to reduce cognitive load',text:'When writing the conversation guidelines, I referred to NN/g’s (Nielsen Norman Group) design guidelines for voice user interfaces (VUI). One key principle: voice has no screen for users to skim or rescan, so information must be revealed in chunks sized to what the user can handle in the moment. I therefore required the AI not to read out every option or detail at once, but to follow the rhythm of the conversation — giving only the information needed for the next step, and pausing to confirm before moving deeper. This principle was written into the Policy document and became a baseline rule for every ordering conversation flow.',imgId:'aca-flow-3',noImage:true},
{text:'Beyond how much information to reveal, I also documented several situations where, without guidelines, the AI clearly didn’t sound like a human agent — or even came across as unprofessional — and added them to the guidelines:',noImage:true},
{title:'• Don’t read out system terms when a lookup fails',text:'When a lookup failed, the AI used to read out system-level error messages directly — wording that doesn’t help users at all and only confuses them more. The guidelines replaced this with phrasing users can understand and that makes them feel taken care of.',noImage:true},
{title:'• Describe dishes in a professional, hospitality-appropriate tone',text:'After querying the menu via an MCP tool, the AI tended to introduce dishes with system-centric openers like “I see…”. For hotel brands that prize service quality, this phrasing isn’t professional enough. The guidelines changed it to a style closer to a human agent — leading directly with the dish itself and dropping wording like “looking up / I see” that exposes system actions.',noImage:true},
{title:'• Don’t ask follow-ups back-to-back when a guest skips a question',text:'When a guest skipped a required detail, the AI used to ask about it immediately in the next line, which could make the conversation feel pushy. The guidelines introduced a “confirmation checkpoint,” letting the AI confirm at the end of the flow whether all required information was collected, instead of interrupting the guest every time something was missed.',noImage:true},
{title:'• Don’t transfer to a human just because an answer can’t be found',text:'When guests asked about something not spelled out on the menu, the AI used to say it didn’t know right away and transfer to a human agent. That turned every small unanswerable question into a burden on real staff, defeating the purpose of introducing an AI agent to relieve staffing pressure. The guidelines changed this so the AI offers options and lets guests choose: note the request in the order remarks and keep the order moving, or actually get help from a human. The decision to transfer goes back to the guest, rather than being the AI’s automatic default.',noImage:true},
{text:'The issues above, pulled from real conversations, weren’t fixed one-off and forgotten. Every time I found an unnatural situation like these, I followed the same method to turn it into a guideline the AI could genuinely follow:',noImage:true},
{title:'Turning discovered issues into guidelines',noImage:true},
{title:'• Categorize the issue first, then identify the root cause',text:'Is it an unclear guideline, incomplete data, or a gap in the flow? This gives every change a clear rationale and makes it easier to align with the team.',imgId:'aca-flow-4'},
{title:'• Write guidelines as Do / Don’t',text:'Replace vague descriptions with explicit behavioral rules, reducing room for the AI to interpret on its own — and letting the engineering team implement directly from them.',noImage:true},
{title:'• Restructure the RAG knowledge base the AI queries',text:'Consolidate the scattered information hotels provide into a consistent structure, so the AI retrieves more accurately and answers more reliably.',noImage:true},
{title:'• Build a Claude Skill to speed up validation',text:'Figuring out “what did the AI base this line on” used to mean time-consuming manual digging through back-office data. On my own initiative, I built a Skill that automatically connects to Grafana and lists the MCP tools the AI called and the KB data it queried in a given call — cutting validation time from manual investigation down to a few seconds.',imgId:'aca-flow-6',imgId2:'aca-flow-6b',natural:true}
]},
{heading:'Results & Impact',type:'text',items:['Conversation flows became noticeably smoother, and the AI asks fewer unnecessary questions, greatly reducing guests’ cognitive load on the phone. At the same time, the clear guideline structure made it easier for the engineering team to implement, and cut the time spent on subsequent regression testing.']},
{heading:'Reflection',type:'text',items:['Systems thinking for voice experiences has to be grounded in real data — many problems can’t be spotted through logical reasoning alone. Only by laying out a large volume of real conversations can you capture how users actually speak and all the unexpected situations, and work backward to design guidelines that truly hold up.']}
]},
{id:'guestweb',highlight:'One hotel saved 384 phone calls a month',projectType:'UX Research · Design System · Web UI Design',platform:'Web (guest-facing in-room interface + hotel admin back office)',timeline:'2024 – Now',coverHeadline:'One system, endless styles',labels:['UX Research','Design System','Web UI Design'],tag:'Multi-brand Website',pairTag:'Content Management System',year:'Systems Thinking',title:'GuestWeb Hotel Digital Concierge',
scope:'Design system lead · Requirements translation · Cross-team coordination',collaborators:'PM · Frontend & backend engineers · Hotel brand contacts',
oneLiner:'A hotel-branded front desk web page guests open by scanning a QR code, managed by hotels through a SaaS back office — a digital concierge system where multiple brands share one architecture while each keeps its own style.',
blocks:[
{heading:'Background',type:'text',title:'This system lets every hotel quickly launch a service website that feels “built for their brand” — while all of them run on one shared, maintained architecture',items:['GuestWeb is a hotel digital concierge system: guests scan an in-room QR code to open a dedicated front desk web page where, from pre-arrival to check-out, they can look up information and order food, request deliveries, book rides, arrange laundry, and more — all without downloading an app. This greatly increases adoption and drives hotel revenue growth. Hotels manage content and services through a SaaS back office.','Every hotel wants a dedicated web page that matches its brand, and wants to launch it quickly on its own without relying on engineers for custom work. That meant I had to design a highly flexible system of page templates and components, paired with a simple, easy-to-learn editing back office, turning customization into something hotels could do themselves.']},
{heading:'Results at a Glance',type:'cards',items:[
{compact:true,title:'Revenue growth',text:'Partner hotels’ F&B revenue grew after launch',detail:'Holiday Inn: about NT$270K in monthly F&B revenue and 450 orders after launch.\niHotel: about NT$160K in monthly revenue and 490 orders.',noImage:true},
{compact:true,title:'Staff time saved',text:'Some brands save hundreds of phone calls per month',detail:'Hotel Clover saved 384 phone calls in one month, while receiving 204 proactive guest inquiries.',noImage:true},
{compact:true,title:'Development cost efficiency',text:'New brands launch without building a new system; the shared architecture greatly reduces maintenance and scaling costs',noImage:true}
]},
{heading:'Problems & Challenges',type:'bullets',items:['Widely varying style expectations: Japanese hotels value complete information, luxury brands value atmosphere and whitespace — every standard differs','Drawing the line on customization: the architecture must be flexible enough, without spiraling into runaway maintenance costs','Complex multi-role scenarios: front desk, housekeeping, and F&B staff work differently, requiring interviews and competitive research to reflect real needs']},
{heading:'A Real Case Behind the Challenge',type:'text-image',items:[{noImage:true,title:'Assumption',text:'The initial MVP had a single default interface with a middle-ground text-to-image ratio, targeting the needs of small business hotels.'},{imgId:'guestweb-case-issue',ratio:'1/1',title:'What We Found',text:'As our client base expanded, interviews and interface proposals revealed that hotels with different positioning had drastically different expectations for the text-to-image ratio — luxury hotels wanted images as full-bleed as possible, with text only as an accent to create atmosphere; Japanese hotels were the opposite, preferring high information density and thorough, detailed text to make users feel reassured.'},{noImage:true,title:'The Pivot',text:'Realizing a single default style couldn’t cover both ends of the spectrum, we shifted from “one fixed ratio” to “a design system where the text-to-image ratio can be flexibly configured to match each brand.”'}]},
{heading:'Implementation After the Pivot',type:'text-image',items:[{imgId:'guestweb-case-impl',title:'A Design System with Configurable Text-to-Image Ratios',ratio:'4/3',text:'To let one system serve both extremes — “atmosphere-driven” and “information-driven” — I broke the text-to-image ratio down into configurable design specs rather than hard-coding it into layouts. Below are interface proposals for hotels with different positioning, along with the corresponding design spec documents:'},{noImage:true,title:'Free Layout vs. Grid System: Finding the Balance with Engineering',text:'At first I wanted the back-office layout to be as free as Webflow, but the engineers pointed out that it would require calculating device widths on the fly, which would be costly to maintain. So I switched to a grid system with a few predefined sizes; after a component is placed, the back office shows how much space is left. From a product-positioning view, tools like Webflow are also built on a grid underneath, hidden behind a more complex editor, because “free layout” is their selling point and worth heavy investment. GuestWeb is an internal tool with a limited set of page types, so there was no need to build a Webflow-grade engine; trading a little flexibility for lower maintenance cost was well worth it. Hotels found the compromise flexible enough, engineering had no maintenance worries, and the team agreed — it shipped smoothly.'}]},
{type:'text-image',items:[{imgId:'guestweb-3-1',ratio:'1.9/1',title:'Systematized Flexibility: Designing the Boundaries of Customization',text:'I broke page styles down into spec templates hotels can adjust intuitively in the back office — layout, color scheme, and chatbot welcome message are all self-configurable. Components share unified specs and can be swapped independently, so maintenance costs don’t spiral as customization grows.'},
{imgId:'guestweb-3-1-r',natural:true}]},
{heading:'My Role & Process',type:'text-image',items:[
{noImage:true,title:'Exploring and Distilling Real Needs',text:'I interviewed hotel staff and visited their workplaces on site, observing how front desk, housekeeping, and F&B staff actually work, rather than assuming needs out of thin air. I also took the initiative to use AI to quickly build interactive prototypes — both as an interview tool to gather requirements faster, and as material for internal usability testing, so assumptions could be validated or disproven early.'},
{pairIds:['guestweb-3-0b','guestweb-3-0c']},
{imgId:'guestweb-3-0'},
{imgId:'guestweb-3-0d',natural:true,caption:'Using an AI-built mock website to test users’ mental models when operating the back-office system'},
{noImage:true,title:'Two Opposite Mental Models',text:'When designing the CMS, the team didn’t know the target users’ mental model of “building a website” — how they understand the relationship between content and containers. Through interviews with hotel marketers and usability tests with marketing colleagues in-house, we found most people prefer to see the overall structure first (a high-fidelity preview) before deciding where to place smaller components. So the first page of the CMS back office was designed to show a high-fidelity preview of the guest-facing interface first, then let users drill down into editing details.\n\nHowever, when designing the menu and product management back office for in-room dining, the same interviews and usability tests led to the exact opposite conclusion: hotel staff prefer to build a complete product library and menu items first, then publish them to the menu one by one — a “small to large” rather than “large to small” workflow.'},
{imgId:'guestweb-mental-model',ratio:'4/3',title:'The Solution',text:'Based on these two opposite mental models, I designed separate information architectures and workflows for the CMS and menu management, rather than applying a single “standard answer.” The same user (hotel staff) can have completely different mental models for different tasks — design must follow the logic of the task itself, not uniformly apply the same interface conventions.'},
{imgId:'guestweb-3-2',title:'Tokenizing the Back-Office Design System into an AI Skill',text:'On my own initiative, I organized the specs into a format AI can read, so it can quickly generate design proposals for validation based on existing guidelines, instead of hand-crafting everything from scratch each time. The output goes straight into discussions with engineering and usability testing, greatly shortening the validation cycle.'}
]},
{heading:'Results & Impact',type:'text-image',items:[
{noImage:true,title:'Hotel Feedback',text:'“This channel lets us engage with guests in a better way — not only keeping them up to date on the latest offers in real time, but also ensuring they never miss any information, for a smoother, more engaging stay.” — Holiday Inn & Suites Saigon Airport.\n“Since we started working together, our F&B revenue has grown 30× compared to the same period, and the Aiello Voice Assistant is the best low-friction ordering tool on the market today.” — iHotel.'}
]},
{heading:'Reflection',type:'text',items:['Customized home page styles and in-room dining menu settings also have to match the data formats of each hotel’s existing ordering system — design can’t only consider whether screens look good; it has to trace back to whether the underlying data actually lines up.']},
{type:'text-image',items:[{imgId:'guestweb-3-1b'}]},
]},
{id:'tms',tag:'Research-Driven Product Design',year:'Research Methods',title:'TMS Portal / StaffApp',
scope:'Visited hotel sites and interviewed staff across departments, translating insights into interface design decisions',collaborators:'Housekeeping, Front Desk, Maintenance, Product Team',
oneLiner:'A highly customizable smart task platform that automatically assigns tasks based on how each hotel operates, boosting staff efficiency, streamlining operations, and delivering actionable data insights.',
blocks:[
{heading:'Background',type:'text',items:['TMS helps hotels manage tasks across departments, automatically assigning them to the right staff based on workflows. It’s also the back-office system hotels use to configure in-room TV menu content, in-house push notifications, guest wake-up calls, and more.']},
{heading:'Problems & Challenges',type:'text',items:['Different hotels focus on different tasks. The core challenge was letting staff in different roles quickly find what’s useful to them on the same screen, without making it cluttered.']},
{heading:'Research Methods',type:'bullets',items:['Visited hotel service areas in person to understand how departments like housekeeping, front desk, and maintenance work together, and interviewed hotel staff about their day-to-day working habits.','Synthesized interview findings into usable insights, clarifying each role’s responsibilities and the information they care about most, as a basis for design decisions.','Built a reusable UI component library to rapidly create web prototypes for user testing.']},
{heading:'My Role & Process',type:'text',items:['Organized interview findings into information the team could use, and kept referencing them in subsequent design decisions.']},
{heading:'Solution',type:'text',items:['Adjusted the level of detail shown in the task list, and redesigned the room status overview using the terminology and status-light colors housekeeping staff are familiar with, making information clearer at a glance.']},
{heading:'Results & Impact',type:'text',items:['Improved screen presentation reduced mistaps when staff report task status; a reworked task management view sped up managers’ shift scheduling and cleaning assignments.']},
{heading:'Reflection',type:'text',items:['Only through interviews and on-site visits can you truly understand how users work and solve problems effectively. At the same time, hotel managers and frontline staff often care about different things, and design needs to find a balance between the two.']}
]},
{id:'nexus',highlight:'Shipped in 2021',dark:true,coverNatural:true,coverHeadline:'Readable at a glance, built to look the part.',projectType:'UI Design · Hardware–Software Integration',timeline:'2020',platform:'Streaming controller panel + desktop software',timelineFirst:true,labels:['UI Design','Hardware–Software Integration','Motion Design'],title:'Live Streamer NEXUS',
oneLiner:'A streaming controller and its companion software. Starting from how streamers actually use it mid-broadcast, I built a visual system that makes every state readable at a glance on a small screen, without giving up the bold esports look the product needed.',
scope:'Dynamic UI components for the hardware panel and desktop software, boot animation, LED lighting scripts, icon library, UI string translation',
blocks:[
{heading:'Background',type:'text',title:'Streamers glance at the controller. They don’t study it.',items:['NEXUS is AVerMedia’s live-streaming software, paired with the Live Streamer NEXUS controller. Streamers use the controller’s touchscreen and knobs to switch which PC screen is captured, mix audio channels and trigger hotkeys.','During a stream, their attention belongs to the game and the audience, and the controller only gets a quick look between moments. That shaped every decision: in the split second a streamer looks down, each button has to say what it does and whether it is on.']},
{type:'cards',items:[{title:'Before',text:'Mid-stream, streamers often had to open several programs and adjust audio levels and aspect ratios'},{title:'With NEXUS',text:'Preset multiple streaming scenes, then swipe the controller’s screen to switch between them instantly'}]},
{heading:'Project at a Glance',type:'cards',items:[
{compact:true,noImage:true,title:'Shipped in 2021',text:'Launched as a mass-produced product: AVerMedia Live Streamer NEXUS (model AX310).'},
{compact:true,noImage:true,title:'State readable at a glance',text:'Hotkeys pair each app’s brand color with motion: on is full color and animated, off dims to a dark tone.'},
{compact:true,noImage:true,title:'One look across hardware and software',text:'The same components run on the controller’s touchscreen and in the desktop app, backed by an icon library with five interaction states.'},
{compact:true,noImage:true,title:'A complete visual asset system',text:'A boot animation with a millisecond-timed LED script, custom hotkey icons, and an app icon in 9 sizes from 16 to 1024 px.'}
]},
{heading:'Problems & Challenges',type:'bullets',items:['A glance, not a gaze: streamers look down for a split second mid-stream, so state has to register instantly','A small screen: on the controller’s touchscreen, subtle changes in an icon’s shape are easy to miss','Same function, different channels: once NEXUS integrated platforms like OBS and Twitch, buttons with the same function but for different channels could appear on the same page, and had to be told apart at a glance','Two displays, one component: the same UI appears on the hardware touchscreen and in the desktop software','Clarity without losing flair: this is a product for streamers and gamers, so it also has to look bold and polished']},
{heading:'Design Decisions',type:'text-image',items:[
{title:'Designing for a glance: from text labels to color and motion',text:'The original icons marked their state with small ON / OFF text in the corner, which was easy to miss on the small screen. Then the software added integrations with platforms like OBS and Twitch, so buttons with the same function but for different channels could appear on the same page, and they needed to be told apart too.\n\nMy first version separated channels by each button’s overall color family and built the state change into the icon itself. Feedback from my manager and fellow designers was that the contrast could be stronger: streamers change settings quickly mid-stream and can’t always give the interface their full attention.\n\nSo in the final version, each hotkey takes the brand color of its app. When it is on, it shows in full color and is animated; when it is off, it dims to a dark version of the same color. The stronger light-dark contrast and the motion make the state readable even from the corner of the eye.',noImage:true,iconCols:5,iconGrid:['slot-assets/nexus-hotkey-on-1-mixer.gif','slot-assets/nexus-hotkey-on-2-share.gif','slot-assets/nexus-hotkey-on-3-layers.gif','slot-assets/nexus-hotkey-on-4-camera.gif','slot-assets/nexus-hotkey-on-5-record.gif','slot-assets/nexus-hotkey-off-1-mixer.png','slot-assets/nexus-hotkey-off-2-layout.png','slot-assets/nexus-hotkey-off-3-layers.png','slot-assets/nexus-hotkey-off-4-store.png','slot-assets/nexus-hotkey-off-5-record.png','slot-assets/nexus-hotkey-blue-1-folder.gif','slot-assets/nexus-hotkey-blue-2-mixer.gif','slot-assets/nexus-hotkey-blue-3-sound.gif','slot-assets/nexus-hotkey-blue-4-seat.gif','slot-assets/nexus-hotkey-blue-5-play.gif']},
{title:'• Customizable, without breaking the system',text:'NEXUS also offers an online editor where streamers set their own hotkey background colors and images. I drew a set of icons in different styles for them to choose from, so personalized layouts still look polished on the controller.',noImage:true,iconCols:5,iconGrid:['slot-assets/nexus-custom-1-guitar.png','slot-assets/nexus-custom-2-award.png','slot-assets/nexus-custom-3-kaomoji.png','slot-assets/nexus-custom-4-moon.png','slot-assets/nexus-custom-5-device.png']},
{title:'One visual language across hardware and software',text:'The desktop app is built on a dark base to match the controller. I drew a library of clean, line-based icons that follow the product’s visual guidelines, and defined every interaction state (Normal, Mouse over, Click, Disable and Focus) so each one has a clear spec.',imgId:'nexus-icon-library',natural:true},
{title:'Visual flair that carries the brand: boot animation and lighting',text:'Clarity sets the rules, but the product also has to feel exciting the moment it powers on. Taking a flashy esports style as the concept, I animated the AVerMedia logo for the controller’s boot screen and designed LED effects that flash in time with the animation.',imgId:'nexus-boot',natural:true},
{title:'• Lighting scripts timed to the millisecond',text:'The lighting changes are fast and intricate, so I followed each lighting pattern and wrote the script precisely, millisecond by millisecond.',imgId:'nexus-light-script',natural:true},
{title:'• App icon',text:'Taking the controller’s knobs as the concept and pairing them with the software’s signature orange, I drew the app icon in 9 sizes, from 16 px to 1024 px, so it reads clearly at every size.',imgId:'nexus-app-icon',natural:true}
]},
{heading:'Final Product',type:'text-image',items:[{imgId:'nexus-final',natural:true}]},
{heading:'Reflection',type:'text',items:['NEXUS taught me to start from the usage context and design operations that span hardware and software as one experience. A streamer’s attention is on the game and the audience, so the lighting on the controller, the buttons on its touchscreen and the settings in the desktop software can’t be treated as separate interfaces. Together they have to answer one question: what does the user need to know in that moment?','If I did it again, I would test the hotkeys in real live-streaming sessions rather than relying on design reviews alone, and track how they are used after launch, to validate that the dimmed off state stays readable under real lighting and in the middle of a stream.']}
]},
{id:'1177pay',highlight:'Clearer bills, easier card binding',coverNatural:true,projectType:'UI Design · B2C Mobile Payment',timeline:'2021 – 2023',platform:'Mobile App',timelineFirst:true,coverHeadline:'Making bill payment quick and easy, starting from the very first payment.',labels:['UI Design','B2C Mobile Payment'],title:'1177PAY Mobile Payment App',
scope:'Bill details, donation page, card-binding flow, widget, loading animation, flowcharts, Design Guideline maintenance',collaborators:'PO · Other designers',
blocks:[
{heading:'Background',type:'text',items:['1177PAY offers secure, versatile mobile payment services. Users can link credit cards, bank accounts and e-invoice mobile barcodes to complete payments quickly and simply. Through app push notifications, they receive bills and payment confirmations in real time, making bills easy to manage.','Product positioning: offer a convenient, fast way to pay bills, guiding people who first use the company’s payment services to download the 1177PAY app, and growing them into loyal members.','Several designers worked on the app. My part focused on how information is ordered in bill details, the main screen for browsing charities on the donation page, the card-binding flow, and visual details such as the widget and the loading animation.']},
{heading:'Project at a Glance',type:'cards',items:[
{compact:true,noImage:true,title:'Bills and donations',text:'Reordered the information in bill details, and redesigned the main screen for browsing charities on the donation page.'},
{compact:true,noImage:true,title:'Easier card binding',text:'Showed each card’s issuing bank logo, and improved the camera screen for scanning a credit card and filling in its details automatically.'},
{compact:true,noImage:true,title:'Visual details',text:'A widget in light and dark mode, a loading animation made in After Effects, and the App Store screenshots.'}
]},
{heading:'Problems & Challenges',type:'bullets',items:['Converting first-time users: many people meet 1177PAY through the company’s payment services rather than the app store, so the app has to show its value right away.','Complex payment flows: payments involve many checkpoints and branches, which have to be documented clearly enough for engineers to build.','Trust when adding a card: linking a credit card is a sensitive step, so users need to recognize their card and understand what the camera is doing.','Keeping a growing product consistent: as new features are added, the Design Guideline has to stay up to date so every screen still feels like the same product.']},
{heading:'Design Decisions',type:'text-image',items:[
{title:'Turning requirements into screens',text:'Working with the PO, I designed screens from the wireframes and wrote the design specifications.',imgId:'pay-screens',natural:true},
{title:'• Making card binding easier to trust',text:'Each card now shows its issuing bank’s logo, so users can recognize it at a glance. I also improved the camera screen used to scan a credit card and fill in its details automatically, making the process easier to understand and use.',noImage:true},
{title:'• Bill details and donations',text:'I reordered the information in bill details, and redesigned the main screen where users browse charities on the donation page.',noImage:true},
{title:'• Widget design',text:'Designed in both light and dark mode.',imgId:'pay-widget',natural:true},
{title:'• Loading motion design',text:'Inspired by a wallet’s snap button opening, I created the loading animation in After Effects.',imgId:'pay-loading',natural:true},
{title:'• Color palette',text:'Built on the blue of the company’s corporate identity, paired with grays and whites for a clean, trustworthy feel.',imgId:'pay-color',natural:true},
{title:'Flowcharts',text:'From the finished screens, I drew flowcharts marking checkpoints and screen transitions.',imgId:'pay-flow',natural:true},
{title:'Design handoff',text:'I delivered the designs and sliced assets through Sketch and Zeplin.',imgId:'pay-handoff',natural:true}
]},
{heading:'Results',type:'text',items:['My work covered bill details, the donation page and the card-binding flow, along with the widget, loading animation, flowcharts and App Store screenshots, and I kept the Design Guideline up to date as features were added.']},
{heading:'Reflection',type:'text',items:['In a payment product, trust is built in the details: a familiar bank logo on each card, a clear state at every checkpoint, and reminders that arrive before users have to think about their bills.']},
{heading:'Final Product',type:'text-image',items:[{imgId:'pay-feature-pay',natural:true},{imgId:'pay-feature-push',imgId2:'pay-feature-scan',natural:true}]}
]},
{id:'17backstage',highlight:'Proposal adopted company-wide',coverNatural:true,projectType:'UI Design · B2B Back Office',timeline:'2021 – 2023',platform:'Web back office',timelineFirst:true,coverHeadline:'Turning a templated back office into a clear, consistent system for small merchants.',labels:['UI Design','B2B Back Office','Redesign'],title:'1177 Tech Merchant Back Office',
scope:'Redesign proposal, layout and interaction design, Design Guideline, wireframes, mockups and handoff',collaborators:'Company leadership · Product manager · Frontend engineers',
blocks:[
{heading:'Background',type:'text',title:'Small merchants needed a simpler way to accept payments',items:['1177 Tech provides third-party payment collection, letting merchants accept credit cards, convenience-store payments and virtual-account transfers on their own online store platforms.','The back office was being built as an MVP for small merchants that need to collect small payments, and for charities that need a donation platform. Many of them don’t want to spend the time and money to apply for a card terminal or a mobile payment service like LINE Pay, so the goal was a collection platform that is quick to apply for and intuitive to use.','The first version was built on a template, and the company’s leadership felt it wasn’t intuitive enough to use. As the company’s only UI designer at the time, I was responsible for the redesign.']},
{heading:'Project at a Glance',type:'cards',items:[
{compact:true,noImage:true,title:'Proposal adopted company-wide',text:'Leadership chose my redesign proposal and asked me to apply its design guideline to every product line in the company.'},
{compact:true,noImage:true,title:'The only designer, end to end',text:'From the proposal and the Design Guideline to wireframes, mockups and handoff, I designed the whole system.'},
{compact:true,noImage:true,title:'Three layout improvements',text:'A top menu set apart from content, detail pages shown as popups, and a collapsible step bar for long forms.'}
]},
{heading:'Problems & Challenges',type:'bullets',items:['Too much information: the back office holds a lot of data, so the goal was to present it in an organized way and let users quickly find the features they need.','Unclear hierarchy: the old menu was stacked vertically on the left, next to data that was also listed vertically, so the two were easy to mistake for the same level of information.','Endless scrolling: details were listed one per line, making pages very long while the right half of the screen sat mostly empty.','Cramped forms: the step bar on the left of form pages squeezed the width of the form itself.','Easy-to-miss errors: errors in the application form were shown only as text, so users could easily overlook them.']},
{heading:'Design Decisions',type:'text-image',items:[
{title:'Leading with the reasoning: a proposal built around how people read',text:'Instead of only presenting new screens, I put together a full proposal deck explaining why every component in the layout sits where it does: following the natural reading order, guiding the eye through the page, and making the guidance around destructive actions clear. Leadership chose this proposal, and it became the basis of the new Design Guideline.',noImage:true},
{title:'Reorganizing the screen layout',text:'In the old version, the menu was stacked vertically on the left of the screen. The back office also lists a lot of data vertically, so the two looked too similar and were easy to mistake for the same level of information. The new version moves the menu to the top, and adds a shadow and a different background color to set it apart from the page content.\n\nI also considered keeping the side menu and only refining its visual hierarchy, but there were so many menu items that it would still take up too much of the screen and pull attention away from the content.',imgId:'bs-layout',natural:true},
{title:'Rearranging detail pages, so users no longer scroll endlessly',text:'In the old version, information was listed one item per line, which made pages too long and left most of the right half of the screen empty. We split the information into columns and set wrapping rules based on the length of each field, keeping the layout neat and comfortable to read. We also turned the detail page into a popup, so users can more easily cross-check several records.',imgId:'bs-detail',natural:true},
{title:'Consolidating form pages',text:'The form pages used to show the step bar on the left, squeezing the width of the form content. I changed the step bar into an expandable, collapsible structure, so users can quickly open the specific section they want to fill in or edit.',imgId:'bs-form',natural:true},
{title:'• Earlier, clearer error messages',text:'Errors used to appear only as text. Now users are warned before they move on to the next step, with an icon so nothing gets missed. Each field also shows a visual cue for its progress and state.',imgId:'bs-form-hints',natural:true},
{title:'A new Design Guideline',text:'Based on the results of the visual proposal, I built a component library shared across the team, keeping designs consistent between different systems. Leadership then asked me to apply it to every product line in the company, and the visual designer also used it for marketing materials.',pairIds:['bs-guide-input','bs-guide-dropdown','bs-guide-icon-btn','bs-guide-font']},
{title:'Discussing wireframes',text:'I used wireframes to discuss component usage and screen layouts with the product manager.',imgId:'bs-wireframe',natural:true},
{title:'Building mockups',text:'I designed the screens in Sketch and uploaded them to Zeplin for handoff to the frontend engineers.',noImage:true}
]},
{heading:'Final Product',type:'text-image',items:[{imgId:'bs-final-1',natural:true},{imgId:'bs-final-2',natural:true},{imgId:'bs-final-3',natural:true},{imgId:'bs-final-4',natural:true},{imgId:'bs-final-5',natural:true}]},
{heading:'Results',type:'text',items:['The back office was still an MVP and hadn’t launched yet, so its impact showed inside the company: leadership adopted my proposal, the Design Guideline was applied to every product line, and the visual designer also used it for marketing materials.']},
{heading:'Reflection',type:'text',items:['This project taught me that a redesign is won by its reasoning, not just its screens. Explaining layout decisions through reading order, visual flow and the risk of each action is what convinced leadership, and it turned one product’s redesign into a guideline for the whole company.']}
]}
];
// Page variant, picked by URL: ?focus=ai leads with the AI voice work; ?focus=hardware leads with
// hardware–software work (?focus=automotive is the same with a motion-focused tagline); no param = default site (older ?focus=fintech links land here too).
// pairs:true lays every card out two per row instead of making the first card full width. aboutIntro / career (keyed by company) override the About page copy.
window.SITE_VARIANT=(()=>{
const focus=new URLSearchParams(window.location.search).get('focus');
if(focus==='hardware'||focus==='automotive'){
const hw={
order:['ai-butler','nexus','guestweb','aca-ai'],
pairs:true,
aboutIntro:'UI/UX designer with 5 years of experience, focused on products where hardware and software meet: from a live-streaming controller’s touchscreen and lighting to an AI smart speaker in hotel rooms. I start from the device’s environment, the context it is used in and the people who use it, then turn engineering constraints into clear, scalable design systems.',
career:{'Aiello':'Designing the AVA in-room smart speaker’s on-device interface, AI voice conversation experience and IoT controls (TV, lighting), plus AI phone ordering and hospitality SaaS products','AVerMedia':'Design internship | Live Streamer NEXUS controller: dynamic UI for the touchscreen and desktop software, boot animation, LED lighting scripts, icon library and app icon'},
headline:'Clarity between\npeople and devices.',
tagline:'Luna・UI/UX Designer・Hardware–Software Experiences',
resumeUrl:'https://drive.google.com/drive/folders/1U047kGSj6b7uZfmoTVgLbatRQR5mA4kY?usp=sharing'
};
// ?focus=automotive: the hardware variant with a motion-focused tagline, for in-vehicle / embedded UI roles.
return focus==='automotive'?{...hw,order:hw.order.concat(['17backstage','1177pay']),resumeUrl:'https://drive.google.com/drive/folders/1AvHO931eBC_5MsxLfNGtAgOee26VIhp2?usp=sharing',tagline:'Luna・UI/UX Designer・Hardware–Software UI & Motion'}:hw;
}
if(focus==='ai') return {
order:['aca-ai','ai-butler','guestweb','17backstage','1177pay'],
headline:'Designing AI that\nlistens, then acts.',
tagline:'Luna・UI/UX Designer・Conversational AI & Smart Devices',
resumeUrl:'https://drive.google.com/drive/folders/1kColvmaOikbEV8f8Nej0tayngMJpFT3f?usp=sharing'
};
return {
order:['guestweb','aca-ai','ai-butler','17backstage','1177pay'],
headline:'Clarity between\npeople and AI.',
tagline:'Luna・UI/UX Designer・AI SaaS Products',
resumeUrl:'https://drive.google.com/drive/folders/1XALJ8GZUo-nuZVn3wBFxr7idXlIw1IAG?usp=sharing'
};
})();
